"""Fix all

Revision ID: 79ce3f04c1d6
Revises: 4a68d155b5c9
Create Date: 2025-11-29 20:29:20.142412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79ce3f04c1d6'
down_revision: Union[str, Sequence[str], None] = '4a68d155b5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('recipients', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_email_analyses_id'), 'email_analyses', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.add_column('emails', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('analysis_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'emails', ['public_id'])
    op.create_foreign_key(None, 'emails', 'email_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'emails', 'groups', ['group_id'], ['id'])
    op.drop_column('emails', 'summary')
    op.drop_column('emails', 'topic')
    op.drop_column('emails', 'tags')
    op.drop_column('emails', 'receiver')
    op.drop_column('emails', 'sender')
    op.drop_column('emails', 'analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('receiver', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('emails', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='unique')
    op.drop_column('emails', 'analysis_id')
    op.drop_column('emails', 'group_id')
    op.drop_column('emails', 'public_id')
    op.drop_table('groups')
    op.drop_index(op.f('ix_email_analyses_id'), table_name='email_analyses')
    op.drop_table('email_analyses')
    # ### end Alembic commands ###
