"""Add timestamp to Analysis

Revision ID: b7a41c26f26d
Revises: 0eac1640a541
Create Date: 2025-11-30 11:00:34.287923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a41c26f26d'
down_revision: Union[str, Sequence[str], None] = '0eac1640a541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_analyses', sa.Column('timestamp', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_analyses', 'timestamp')
    # ### end Alembic commands ###
